name: LimitedSpectator
version: 1.0.0
description: Spectator mode for limited set of users
author: fulcanelly
website: ${url}
api-version: 1.16
depend:
  - tg-bridge

  
main: me.fulcanelly.limitspect.LimitedSpectator

commands:
  spectator:
    description: chnages gamemode to spectator
    usage: /tg <params> 

